=== command
CI="true" GITHUB_ACTIONS="true" GITHUB_EVENT_NAME="pull_request" GITHUB_REPOSITORY="project_name/project_name" GITHUB_RUN_ID="35" GITHUB_ACTOR="some_test_username" GITHUB_REF="some/branch-name" GITHUB_EVENT_PATH="<MASKED>" SEMGREP_APP_TOKEN="fake-key-from-tests" SEMGREP_USER_AGENT_APPEND="pytest" SEMGREP_SETTINGS_FILE="<MASKED>" SEMGREP_VERSION_CACHE_PATH="<MASKED>" SEMGREP_ENABLE_VERSION_CHECK="0" SEMGREP_SEND_METRICS="off" semgrep ci --debug --no-force-color
=== end of command

=== exit code
2
=== end of exit code

=== stdout - plain

=== end of stdout - plain

=== stderr - plain
Scan environment:
  versions    - semgrep <MASKED> on python <MASKED>
  environment - running in environment github-actions, triggering event is pull_request
<MASKED> <MASKED> <MASKED>s<MASKED>e<MASKED>r<MASKED>v<MASKED>e<MASKED>r<MASKED> <MASKED> <MASKED> <MASKED> <MASKED> <MASKED> <MASKED>-<MASKED> <MASKED>h<MASKED>t<MASKED>t<MASKED>p<MASKED>s<MASKED>:<MASKED>/<MASKED>/<MASKED>s<MASKED>e<MASKED>m<MASKED>g<MASKED>r<MASKED>e<MASKED>p<MASKED>.<MASKED>d<MASKED>e<MASKED>v<MASKED>

head branch (bar) has latest commit 17b3114fb3d41437abc2a3e6499db84ad921e6f0, fetching that commit now.
Trying to shallow fetch branch foo from origin
base branch (foo) has latest commit f7ee3123ed098941662685dd8b726fceee48f78d
Fixing git state for github action pull request
Calling git rev-parse HEAD
stashed_rev: 17b3114fb3d41437abc2a3e6499db84ad921e6f0
Not on head ref: 17b3114fb3d41437abc2a3e6499db84ad921e6f0; checking that out now.
Attempting to find merge base, attempt_count=0, fetch_depth=0
Attempting to find merge base, attempt_count=1, fetch_depth=4
Trying to fetch branch foo from origin as base branch
Trying to fetch branch bar as commit from origin as head branch tip commit
Using f7ee3123ed098941662685dd8b726fceee48f78d as the merge-base of f7ee3123ed098941662685dd8b726fceee48f78d and 17b3114fb3d41437abc2a3e6499db84ad921e6f0
Fetching configuration from semgrep.dev
Getting scan configurations
Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/app/scans.py", line 97, in get_scan_config
    response.raise_for_status()
  File "/home/runner/.local/share/virtualenvs/cli-uZ-2zvZl/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://semgrep.dev<MASKED>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/commands/ci.py", line 300, in ci
    scan_handler.get_scan_config(metadata_dict)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/app/scans.py", line 99, in get_scan_config
    raise Exception(
Exception: API server at https://semgrep.dev<MASKED>

Could not start scan API server at https://semgrep.dev<MASKED>

Returning to original head revision 17b3114fb3d41437abc2a3e6499db84ad921e6f0
Not sending pseudonymous metrics since metrics are configured to OFF and registry usage is False

=== end of stderr - plain