=== command
BUILD_BUILDID="some_id" BUILD_REPOSITORY_URI="https://github.com/project_name/project_name.git" SYSTEM_PULLREQUEST_SOURCEBRANCH="some/branch-name" SYSTEM_TEAMFOUNDATIONSERVERURI="https://azure.pipeline.url/" SYSTEM_TEAMPROJECTID="project_id" SYSTEM_JOBID="job_id" SYSTEM_TASKINSTANCEID="task_id" SYSTEM_PULLREQUEST_SOURCECOMMITID="<MASKED>" SEMGREP_APP_TOKEN="fake-key-from-tests" SEMGREP_USER_AGENT_APPEND="pytest" SEMGREP_SETTINGS_FILE="<MASKED>" SEMGREP_VERSION_CACHE_PATH="<MASKED>" SEMGREP_ENABLE_VERSION_CHECK="0" SEMGREP_SEND_METRICS="off" semgrep ci
=== end of command

=== exit code
2
=== end of exit code

=== stdout - plain

=== end of stdout - plain

=== stderr - plain
Scan environment:
  versions    - semgrep <MASKED> on python <MASKED>
  environment - running in environment azure-pipelines, triggering event is unknown
  server      - https://semgrep.dev

Fetching configuration from semgrep.dev
Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/app/scans.py", line 96, in get_scan_config
    response.raise_for_status()
  File "/home/runner/.local/share/virtualenvs/cli-uZ-2zvZl/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://semgrep.dev/api/agent/deployments/scans/config

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/commands/ci.py", line 300, in ci
    scan_handler.get_scan_config(metadata_dict)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/app/scans.py", line 98, in get_scan_config
    raise Exception(
Exception: API server at https://semgrep.dev returned this error: {"error":"not found"}

Could not start scan API server at https://semgrep.dev returned this error: {"error":"not found"}


=== end of stderr - plain