=== command
CI="true" GITHUB_ACTIONS="true" GITHUB_EVENT_NAME="push" SEMGREP_REPO_NAME="project_name/project_name" SEMGREP_JOB_URL="customjoburl.com" GITHUB_ACTOR="some_test_username" SEMGREP_PR_ID="312" SEMGREP_PR_TITLE="PR_TITLE" SEMGREP_BRANCH="some/branch-name" GITHUB_SHA="<MASKED>" SEMGREP_APP_TOKEN="fake-key-from-tests" SEMGREP_USER_AGENT_APPEND="pytest" SEMGREP_SETTINGS_FILE="<MASKED>" SEMGREP_VERSION_CACHE_PATH="<MASKED>" SEMGREP_ENABLE_VERSION_CHECK="0" SEMGREP_SEND_METRICS="off" semgrep ci --no-suppress-errors
=== end of command

=== exit code
2
=== end of exit code

=== stdout - plain
                  
                  
┌────────────────┐
│ Debugging Info │
└────────────────┘
                  
  SCAN ENVIRONMENT
  versions    - semgrep <MASKED> on python <MASKED>
  environment - running in environment github-actions, triggering event is push
            
  CONNECTION
  Reporting start of scan for deployment_name         
  Fetching configuration from Semgrep Cloud Platform                 
               
┌─────────────┐
│ Scan Status │
└─────────────┘
  Scanning 4 files tracked by git with 4 Code rules, 2 Supply Chain rules:
            
            
  CODE RULES
  Scanning 1 file with 4 python rules.
                    
  SUPPLY CHAIN RULES
  Scanning 1 file.
This rule contains an unexpected scan source in the metadata: eqeq-bad
Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/commands/ci.py", line 464, in ci
    if rule.scan_source == RuleScanSource.previous_scan:
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/rule.py", line 270, in scan_source
    raise ValueError(f"This rule contains an unexpected scan source in the metadata: {self.id}")
ValueError: This rule contains an unexpected scan source in the metadata: eqeq-bad

=== end of stdout - plain

=== stderr - plain

=== end of stderr - plain