=== command
CI="true" TRAVIS="true" SEMGREP_REPO_NAME="a/repo/name" SEMGREP_REPO_URL="https://random.url.org/some/path" SEMGREP_BRANCH="branch/some-other-branch-name" SEMGREP_JOB_URL="https://another.random.url.org/some/path" SEMGREP_COMMIT="<some_random_commit>" SEMGREP_PR_ID="99999" TRAVIS_REPO_SLUG="project_name/project_name" TRAVIS_PULL_REQUEST_BRANCH="some/branch-name" TRAVIS_JOB_WEB_URL="https://travis.job.web.url/" TRAVIS_PULL_REQUEST="35" TRAVIS_COMMIT_MESSAGE="some: commit message! foo" TRAVIS_COMMIT="<MASKED>" SEMGREP_APP_TOKEN="fake-key-from-tests" SEMGREP_USER_AGENT_APPEND="pytest" SEMGREP_SETTINGS_FILE="<MASKED>" SEMGREP_VERSION_CACHE_PATH="<MASKED>" SEMGREP_ENABLE_VERSION_CHECK="0" SEMGREP_SEND_METRICS="off" semgrep ci --no-suppress-errors
=== end of command

=== exit code
2
=== end of exit code

=== stdout - plain

=== end of stdout - plain

=== stderr - plain
Scan environment:
  versions    - semgrep <MASKED> on python <MASKED>
  environment - running in environment travis-ci, triggering event is pull_request
  server      - https://semgrep.dev

Fetching configuration from semgrep.dev
Authenticated as org_name
[Errno 2] No such file or directory: '/home/runner/work/semgrep/semgrep/cli/src/semgrep/semgrep_interfaces/rule_schema_v1.yaml'
Traceback (most recent call last):
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/commands/wrapper.py", line 35, in wrapper
    func(*args, **kwargs)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/commands/ci.py", line 347, in ci
    ) = semgrep.semgrep_main.main(
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/semgrep_main.py", line 333, in main
    configs_obj, config_errors = get_config(
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/config_resolver.py", line 758, in get_config
    config, errors = Config.from_rules_yaml(config_strs[0])
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/config_resolver.py", line 317, in from_rules_yaml
    parse_config_string(resolved_config_key, config, filename=None)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/config_resolver.py", line 615, in parse_config_string
    data = parse_yaml_preserve_spans(contents, filename)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/rule_lang.py", line 429, in parse_yaml_preserve_spans
    validate_yaml(data)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/rule_lang.py", line 539, in validate_yaml
    jsonschema.validate(data.unroll(), RuleSchema.get(), cls=Draft7Validator)
  File "/home/runner/work/semgrep/semgrep/cli/src/semgrep/rule_lang.py", line 55, in get
    with schema_path.open() as fd:
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/semgrep/semgrep/cli/src/semgrep/semgrep_interfaces/rule_schema_v1.yaml'

=== end of stderr - plain